name: ci
on:
  push:
  pull_request:
  schedule:
  - cron: '0 3 * * *'
jobs:
  test:
    timeout-minutes: 60
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: scala_2
            java: 8
            os: ubuntu-latest
          - name: scala_3
            java: 8
            os: ubuntu-latest
          - name: scala_2
            java: 8
            os: windows-latest
          - name: scala_2
            java: 11
            os: ubuntu-latest
    runs-on: ${{ matrix.os }}
    steps:
    - uses: olafurpg/setup-scala@v12
      with:
        java-version: "adopt@1.${{matrix.java}}"
    - uses: actions/checkout@v2.3.4
    - uses: coursier/cache-action@v5
    - shell: bash
      run: |
        case ${{ matrix.name }} in
          "scala_2")
            sbt -v "+ test" "+ mimaReportBinaryIssues" "+ publishLocal"
            ;;
          "scala_3")
            sbt -v \
            SetScala3_0 \
            compile \
            "all unfiltered-agents/test unfiltered-filter/test unfiltered-filter-async/test unfiltered-filter-uploads/test unfiltered-jetty/test unfiltered-json4s/test unfiltered-netty-server/test unfiltered-scalatest/test unfiltered-specs2/test unfiltered-uploads/test unfiltered-util/test" \
            publishLocal
            ;;
          *)
            echo "unknown job"
            exit 1
        esac
    - shell: bash
      run: rm -rf "$HOME/.ivy2/local" || true
